language: python

python:
  - "2.6"
  - "2.7"

env:
  - DJANGO=django==1.4.5
  - DJANGO=django==1.5

install:
  - "pip install $DJANGO --use-mirrors"

script:
  - python ./manage.py test

matrix:
  allow_failures:
    - env: DJANGO=django==1.5
